# template_reits.py 配置文件

# 数据源 (REITs通常使用不复权数据)
data_src: "custom:OfflineDataAPI.CStockFileReader"

# CChan 配置（结合用户参数 + 稳健版默认）
chan_config:
  # 用户指定参数
  #divergence_rate: 1
  min_zs_cnt: 1
  bs1_peak: false
  bs_type: "1,1p,2,2s,3a,3b"  # 为满足“全部显示”要求，补充 3b
  max_bs2_rate: 0.7

  # 稳健版默认参数
  macd_algo: "peak"
  macd_algo-seg: "slope"
  bsp1_only_multibi_zs: true
  bsp1_only_multibi_zs-seg: false
  bsp2_follow_1: true
  bsp2s_follow_2: true
  max_bsp2s_lv: null
  bsp3_follow_1: true
  strict_bsp3: false
  bsp3_peak: false
  cal_demark: true

# 绘图配置 (只绘制日线相关图表)
plot_config:
  plot_kline: true
  plot_bi: true
  plot_seg: true
  plot_zs: true
  plot_bsp: true
  plot_segbsp: true
  plot_macd: true
  plot_demark: true

# 绘图参数 (默认为空)
plot_para: {}
